version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: postgres:11.6
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: "activity_db,calorie_db,feed_db,notification_db,user_management_db"
  activity:
    platform: linux/x86_64
    build: services/activity
    restart: always
    depends_on:
      - db
    ports:
      - 3000:80
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: activity_db
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: jwt
      HASH_SECRET: hash
      FEED_SERVICE_ENDPOINT: http://feed
      NOTIFICATION_SERVICE_ENDPOINT: http://notification
  calorie:
    platform: linux/x86_64
    build: services/calorie
    restart: always
    depends_on:
      - db
    ports:
      - 3001:80
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: calorie_db
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: jwt
      HASH_SECRET: hash
      NUTRITIONX_APP_ID: ce9582c7
      NUTRITIONX_APP_KEY: b2ee7e4780c2337d0beef51693e406d0
      NUTRITIONX_ENDPOINT: https://trackapi.nutritionix.com/v2
  feed:
    platform: linux/x86_64
    build: services/feed
    restart: always
    depends_on:
      - db
    ports:
      - 3002:80
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: feed_db
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: jwt
      HASH_SECRET: hash
  notification:
    platform: linux/x86_64
    build: services/notification
    restart: always
    depends_on:
      - db
    ports:
      - 3003:80
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: notification_db
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: jwt
      HASH_SECRET: hash
  user-management:
    platform: linux/x86_64
    build: services/user-management
    restart: always
    depends_on:
      - db
    ports:
      - 3004:80
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: user_management_db
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: jwt
      HASH_SECRET: hash
